
import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";

interface AnalysisPopupProps {
  isOpen: boolean;
  onClose: () => void;
  analysisText: string;
  location: string;
}

export const AnalysisPopup: React.FC<AnalysisPopupProps> = ({ isOpen, onClose, analysisText, location }) => {
  if (!isOpen) {
    return null;
  }

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      {/* CORREÇÃO: Define um layout flexível com altura máxima para permitir a rolagem interna */}
      <DialogContent className="max-w-3xl bg-white text-slate-900 flex flex-col max-h-[85vh]">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle>Urban Analysis for {location}</DialogTitle>
          <DialogDescription className="text-slate-600">
             Here is the preliminary plan generated by the AI.
          </DialogDescription>
        </DialogHeader>
        
        {/* A área de rolagem agora cresce para preencher o espaço, ativando a rolagem quando necessário */}
        <ScrollArea className="flex-grow rounded-md border bg-slate-50 p-4">
            {analysisText.split('\n').map((paragraph, index) => (
                <p key={index} className="mb-4 text-sm text-slate-800 last:mb-0">
                    {paragraph}
                </p>
            ))}
        </ScrollArea>

        <DialogFooter className="flex-shrink-0 pt-4">
          <Button onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
